pipeline {
      agent any

      tools {nodejs "nodejs16"}

      stages {
        stage('Build') {
          steps {
            sh 'FE/npm install'
          }
        }


        stage('Run') {
          steps {
            sh 'FE/npm run dev'
          }
        }
      }
}