pipeline {
      agent any

      tools {nodejs "nodejs16"}

      stages {
        stage('Build') {
          steps {
            dir('FE/') {
                sh 'npm install'
            }
          }
        }


        stage('NPM Run Dev') {
          steps {
            dir('FE/') {
                sh 'npm run dev'
            }
          }
        }
      }
}