pipeline {
    agent any
    tools {
        maven 'autoinstalled maven'
    }
    stages {

        stage('Version') {
            steps {
                sh 'mvn --version'
            }
        }

        stage("Compilation") {
           steps {
                dir('BE/') {
                    sh "mvn clean install -DskipTests"
                }
            }
        }
        stage("Tests and Deployment") {
/*             steps {
                echo 'Runing unit tests'
                //sh "./mvnw test -Punit"
             } */
            steps {
                echo 'Deployment'
                sh 'mvn -f BE/ spring-boot:run'
             }
         }
    }
}