pipeline {
    agent {
      docker {
            image 'maven:3.8.3-openjdk-17'
            //label 'datafabric-docker'
            args '-p 8443:8443'
      }
      /*
          dockerfile {
              filename 'Dockerfile'
              dir 'BE'
              //label 'datafabric-docker'
              //additionalBuildArgs  '--build-arg version=1.0.2'
              args '-p 8443:8443'
          }
          */
    }
    stages {

        stage('Version') {
            steps {
                sh 'mvn --version'
            }
        }

        stage("Compilation") {
           steps {
                dir('BE/') {
                    sh "mvn clean install -DskipTests"
                }
            }
        }
        stage("Test") {
           steps {
                dir('BE/') {
                    sh "mvn test"
                }
            }
        }
        stage("Spring-Boot:Run") {
            steps {
                  dir('BE/') {
                      sh 'mvn spring-boot:run -Drun.arguments="--server.environment=prod"'
                  }
             }
         }
    }
}