pipeline {
  agent {
    label 'docker'
  }
    agent {
      docker { image 'maven:3.8.3-openjdk-17' }
    }
    tools {
        maven 'autoinstalled maven'
        dockerTool 'docker'
    }
    stages {

        stage('Version') {
            steps {
                sh 'mvn --version'
            }
        }

        stage("Compilation") {
           steps {
                dir('BE/') {
                    sh "mvn clean install -DskipTests"
                }
            }
        }
        stage("Spring-Boot:Run") {
            steps {
                  dir('BE/') {
                      sh "mvn spring-boot:run"
                  }
             }
         }
    }
}